Repository nextcloud/event_update_notification, pull requests merged in 2022-10, with the labels that each got.

#37 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: dependencies, 3. to review

#41 🌏 Make events clickable if calendar is installed
  CHANGELOG.md
  lib/EventListener.php
  lib/Notifier.php
  tests/psalm-baseline.xml
Labels: enhancement

#45 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#43 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies
