Repository nextcloud/event_update_notification, pull requests merged in 2024-08, with the labels that each got.

#104 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies, 3. to review, automated

#106 fix(shares): Don't notify users that "Unshared" a calendar
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  .gitignore
  .php-cs-fixer.dist.php
  .tx/config.license
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  REUSE.toml
  appinfo/info.xml
  composer.json
  composer.lock
  docs/demo.png.license
  lib/AppInfo/Application.php
  lib/EventListener.php
  lib/Notifier.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/psalm-baseline.xml.license
Labels: bug

#108 chore: Add reuse batch
  README.md
Labels: 3. to review
